-- ===============================================================================
-- Supply Chain & Inventory Analysis Project
-- Query 02: Supplier Lead Time & Performance Analysis
-- -------------------------------------------------------------------------------
-- Purpose:
--   Evaluate supplier delivery speeds, total order fulfillment volume, total spend,
--   and profit generated by vendor.
-- ===============================================================================

-- -------------------------------------------------------------------------------
-- 2.1: Supplier Performance Summary
-- Ranks suppliers by total order volume, average lead time (days), and financial contribution.
-- -------------------------------------------------------------------------------
SELECT 
    Supplier_Name,
    COUNT(*) AS Total_Orders,
    SUM(Units_Sold) AS Total_Units_Sold,
    ROUND(AVG(Shipping_Time_Days), 2) AS Avg_Shipping_Time_Days,
    MIN(Shipping_Time_Days) AS Fastest_Shipping_Days,
    MAX(Shipping_Time_Days) AS Slowest_Shipping_Days,
    ROUND(SUM(Total_Cost), 2) AS Total_Purchase_Cost_INR,
    ROUND(SUM(Profit), 2) AS Total_Profit_Generated_INR
FROM inventory_data
GROUP BY Supplier_Name
ORDER BY Avg_Shipping_Time_Days ASC;


-- -------------------------------------------------------------------------------
-- 2.2: Slow Delivery Analysis (Orders taking > 7 days)
-- Identifies suppliers with high proportions of delayed fulfillments.
-- -------------------------------------------------------------------------------
SELECT 
    Supplier_Name,
    COUNT(*) AS Slow_Orders_Count,
    ROUND(COUNT(*) * 100.0 / SUM(COUNT(*)) OVER(), 2) AS Share_Of_Slow_Orders_Pct,
    ROUND(AVG(Shipping_Time_Days), 2) AS Avg_Slow_Shipping_Days
FROM inventory_data
WHERE Shipping_Time_Days > 7
GROUP BY Supplier_Name
ORDER BY Slow_Orders_Count DESC;
